// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03RC2-KwrpjYiScuCO7z1TjC6lgN0kW8',
    appId: '1:778354037182:web:8b1049208d1c854bec29ef',
    messagingSenderId: '778354037182',
    projectId: 'sm-app-9ed94',
    authDomain: 'sm-app-9ed94.firebaseapp.com',
    storageBucket: 'sm-app-9ed94.appspot.com',
    measurementId: 'G-4ZY6FEEJ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbdPlS9fcUSfUJjQj6cQ5by_H1opzAng',
    appId: '1:778354037182:android:4700d68365463558ec29ef',
    messagingSenderId: '778354037182',
    projectId: 'sm-app-9ed94',
    storageBucket: 'sm-app-9ed94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa3rBbuMFMFE0DzomKTIsWYe1LRvYsgHY',
    appId: '1:778354037182:ios:69c5f926f1d1b869ec29ef',
    messagingSenderId: '778354037182',
    projectId: 'sm-app-9ed94',
    storageBucket: 'sm-app-9ed94.appspot.com',
    iosBundleId: 'com.example.smApp',
  );
}
